### ISSUE TITLE
Compilation error: 'esp_efuse_mac_get_default' was not declared in this scope

### ISSUE THREAD

**Issue by greghall-au** [ssbc/tinySSB#15]
Trying to compile on Arduino IDE 2.3.4
-
I added in lora.h, button2.h & hardware.h
to get to...
-
In file included from /Users/greghall/Documents/GitHub/ssbc/tinySSB/esp32/loramesh-TBeam/loramesh-TBeam.h:9,
                 from /Users/greghall/Documents/GitHub/ssbc/tinySSB/esp32/loramesh-TBeam/loramesh-TBeam.ino:3:
/Users/greghall/Documents/GitHub/ssbc/tinySSB/esp32/loramesh-TBeam/hw_setup.h: In function 'void hw_setup()':
/Users/greghall/Documents/GitHub/ssbc/tinySSB/esp32/loramesh-TBeam/hw_setup.h:169:3: error: 'esp_efuse_mac_get_default' was not declared in this scope
  169 |   esp_efuse_mac_get_default(my_mac);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~

exit status 1

Compilation error: 'esp_efuse_mac_get_default' was not declared in this scope
-
What am I doing wrong?
Maybe a platformio so that library management is handled by the system?
-
Love your work, keen to try it out.
-
